### ISSUE TITLE
AnalogIn test requires that analog input pins also support digital output function

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/ci-test-shield#1]
Need an alternative way to test analog pins when they don't support digital output for some rare cases.  A resistor ladder is preferred such that a different value can be read on each analog pin.  This would confirm that the analog pins are configured correctly for individually measuring on each pin.  
Alternatively, have a way to fly-wire the pwm-capable digital signals (selectable) to a capacitor to ground, then to the resistors in parallel to the analog pins.

**Comment by BlackstoneEngineering** [comment]
As a solution I have added the 'assumptions' tests, which will check the assumptions made in the tests. In this case the `TESTS/assumptions/analogin/analogin.cpp` test will check that the AnalogIn pins can be used as DigitalOut pins. If not then the assumption fails, as does the entire test. Is this an acceptable solution?

**Comment by BlackstoneEngineering** [comment]
@maclobdell  are the assumptions tests an acceptable solution?

**Comment by BlackstoneEngineering** [comment]
Marking as resolved.
