### ISSUE TITLE
K64F Fails to read I2C EEPROM 

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/ci-test-shield#17]
After fixing the other unrelated issue: https://github.com/ARMmbed/ci-test-shield/issues/16

The I2C EEPROM tests fail for K64F.  

```
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target       | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 0      | 3      | FAIL   | 0.5                |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 0      | 1      | FAIL   | 0.8                |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 0      | 3      | FAIL   | 0.47               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR Single Byte       | 0      | 2      | FAIL   | 0.31               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.12               |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
mbedgt: test case results: 4 FAIL / 2 OK
```

After the I2CEeprom library does a write to the EEPROM, it does a sequence of 0-byte writes every 1ms until it gets a ACK indicating the write finished on the EEPROM and it is ready to read.  After it gets an Ack, then the read should happen.

But on the K64F the read doesn’t happen.

It seems that, if a 0-byte write cycle results in an Ack, there is no stop condition afterwards, and the next write cycle that is requested results in Bus Busy error. 

I think that, for compatibility, the K64F hal implementation/driver needs to ensure that 0-byte write sequences (or all write sequences that are finished?), are followed by stop condition to release the bus.

@mmahadevan108

**Comment by mmahadevan108** [comment]
Where is this EEPROM chip located. I could not find it on the application shield board shown below:
https://developer.mbed.org/cookbook/mbed-application-shield

**Comment by mmahadevan108** [comment]
I realized I don't have a test-shield board, can you please try the attached patch.
[0001-KSDK-I2C-Handle-0-byte-write.zip](https://github.com/ARMmbed/ci-test-shield/files/657965/0001-KSDK-I2C-Handle-0-byte-write.zip)

**Comment by BlackstoneEngineering** [comment]
@mmahadevan108 , if you're a partner please reach out to your partner enablement contact and they will send you a couple boards)

**Comment by mmahadevan108** [comment]
Thanks, I have contacted them.

**Comment by maclobdell** [comment]
@mmahadevan108  I tried the patch, seems like an additional tweak is needed.  With the patch the start condition isn't followed up by anything.  Please give it a try on the test shield and let us know.
![image](https://cloud.githubusercontent.com/assets/6129601/21366063/30ed3604-c6c6-11e6-9218-333c54a17d5e.png)

**Comment by 0xc0170** [comment]
@maclobdell If you can retest latest master , there's a fix , I got all OK for i2c tests, using K64F target

**Comment by maclobdell** [comment]
I tested it with the master branch and confirm that everything passes now.  @mmahadevan108   Thanks for the fix!  

`
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| target       | platform_name | test suite    | test case                          | passed | failed | result | elapsed_time (sec) |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 10  Bytes         | 1      | 0      | OK     | 0.32               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 100 Bytes         | 1      | 0      | OK     | 0.73               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR 2 Bytes           | 1      | 0      | OK     | 0.29               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  EEProm WR Single Byte       | 1      | 0      | OK     | 0.16               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  Instantiation of I2C Object | 1      | 0      | OK     | 0.06               |
| K64F-GCC_ARM | K64F          | tests-api-i2c | I2C -  LM75B Temperature Read      | 1      | 0      | OK     | 0.12               |
+--------------+---------------+---------------+------------------------------------+--------+--------+--------+--------------------+
`
