### ISSUE TITLE
Tests - verify that required pins are defined

### ISSUE THREAD

**Issue by 0xc0170** [ARMmbed/ci-test-shield#18]
There can be a case when required pin for instance A1 could be NC (target do not pollute that pin for whatever reason). This would cause failures in tests in later stages. If we test it early, we could identify the problems with pins definitions.

Inspiration from here: https://github.com/ARMmbed/mbed-os/issues/3508#issuecomment-270215572

**Comment by BlackstoneEngineering** [comment]
I think Michael added this here : https://github.com/ARMmbed/ci-test-shield/pull/23
