### ISSUE TITLE
Missing prerequisites for running ci test shield tests

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/ci-test-shield#39]
Need to add to the list of Pre-requisites

- git
- mercurial
- compiler such as GCC, ARM Compiler 5, or IAR

also python modules 

- mbed-ls 
- pyserial
 

For the python modules, how about a requirements file that can ensure they are installed?  Suggest to add a requirements.txt file. 
And add this command to the setup instructions:
`
pip install -r requirements.txt
`

**Comment by 0xc0170** [comment]
This is well know (to mbed OS) requirements. Shoudn't this be documented somewhere as part of mbed OS, and this repository just points to this documentation ?

**Comment by BlackstoneEngineering** [comment]
@maclobdell we can add this to the readme, just to be extra explicit. 
@0xc0170 lets add a line to the readme that says it has the same requirements as mbed-os and then links to the requirements for mbed os?

**Comment by 0xc0170** [comment]
> @0xc0170 lets add a line to the readme that says it has the same requirements as mbed-os and then links to the requirements for mbed os?

PR sent
