### ISSUE TITLE
Prepare repository for production releases

### ISSUE THREAD

**Issue by mray19027** [ARMmbed/ci-test-shield#59]
Make `master` the latest release. Only commits tag with a release tag should be pulled into master.

`development` will be for current development where feature branches will be merged.

`level-testing` planned for Q3 as a feature branch

I will be making these changes later this week

**Comment by BlackstoneEngineering** [comment]
why was this closed?

**Comment by mray19027** [comment]
@BlackstoneEngineering I closed it because I completed it. Are there other things I need to do with the repository to make it 'production grade'

**Comment by BlackstoneEngineering** [comment]
nope, next time just add a message saying 'done' or some such.
