### ISSUE TITLE
Correct deprecated API

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/ci-test-shield#93]
Lots of deprecated API are used with ci-test-shield

- wait_ms
- wait
- gettid

We need to use this shield even after mbed-os 5.14

Thx

@MarceloSalazar 
@LMESTM 
@bulislaw

**Comment by bulislaw** [comment]
@jamesbeyond please have a look

**Comment by jamesbeyond** [comment]
you mean in https://github.com/ARMmbed/ci-test-shield
@jeromecoutant ?

**Comment by jeromecoutant** [comment]
Yes, + I2CEeprom + LM75B

**Comment by jamesbeyond** [comment]
Despite we announced deprecation of those APIs, I'd say we haven't done a good job in terms of deprecating those APIs from our end. Some of our code still uses them. We have a task for cleaning up our deprecated APIs from mbed-os code base, I will make sure those repos will get updated along with the mbed-os

**Comment by jeromecoutant** [comment]
Part of correction in #96

**Comment by jamesbeyond** [comment]
I believe the deprecated API from this repo had been updated. closing this ticket
